### ISSUE TITLE
Downporting (731)

### ISSUE THREAD

**Issue by sbcgua** [abaplint/abaplint-abap-backend#15]
Looking at downporting possibilities ... for the moment stumbled upon 2 issues:

- `/ui5/cl_json_parser` at `zcl_abaplint_json_reader`: will try to replace with `cl_fdt_json=>json_to_data` ? or maybe leave the validation to the backend ???
- IF_T100_DYN_MSG at exception: hmm, what's the heck it this :)))) looks like a combination of `IF_MESSAGE` and `IF_T100_MESSAGE` and a couple of attrs ... do you think I can remove ?

@larshp

**Comment by larshp** [comment]
for the exception, try deleting and creating it again on 731

I dont think IF_T100_DYN_MSG is even 740sp08 compatible, https://blogs.sap.com/2015/11/12/abap-news-for-release-750-converting-messages-into-exceptions/

**Comment by sbcgua** [comment]
much progress ... but `/ui5/cl_json_parser` would be a challenge ...

**Comment by larshp** [comment]
there is some of the built-in XML handling that can also handle JSON, think it can be done

**Comment by sbcgua** [comment]
yeah ... I've actually been struggling though it just in recent days ... extremely unintuitive, unflexible, undebuggable - very complicated ... and I did't succeed. Switched to open source alternatives :) Anyway ... will resolve it somehow.

**Comment by FreHu** [comment]
there is also /ui2/cl_json

**Comment by larshp** [comment]
@sbcgua yea, agree, its not super, and have not looked much into it, but if possible I'd like to avoid a dependency

**Comment by sbcgua** [comment]
@FreHu not in my system :(

for my task I ended up with https://github.com/koemaeda/abap-json. But will need to fine tune it yet. For this one ... I don't know yet. Either will check `cl_fdt_json=>json_to_data` or something custom based on that XML transformation. Leaving this part for the rest.

**Comment by sbcgua** [comment]
@larshp dependency: yeap, I agree.

**Comment by larshp** [comment]
another option

as far as I remember, the sent JSON is built via concatenate. So add a request parameter to request the resonse as XML, and translate the response to XML instead on server side, it might be easier? easy to generate on server, and easy to parse on client

**Comment by sbcgua** [comment]
hmmm. interesting option - I'll consider. 

P.S. almost done with all the code, just that json stuff left... but have to go to eat something first :)

**Comment by sbcgua** [comment]
done

**Comment by sbcgua** [comment]
next is the server side: cleanups and dockerize ...

**Comment by sbcgua** [comment]
I guess can be closed

**Comment by sbcgua** [comment]
Hmm new github app doesn’t allow to close issues. Strange.
