### ISSUE TITLE
"Update from Git" -> Shortdump in private repo

### ISSUE THREAD

**Issue by g-back** [abaplint/abaplint-abap-backend#23]
When using the "Update from Git" function on a private repo, the program dumps.

Cause: the popup for the password prompt from abapgit (`ZCL_ABAPGIT_PASSWORD_DIALOG=>POPUP`) is called with `sy-cprog` , which is `SAPLS_CODE_INSPECTOR` instead of `ZABAPGIT` or `ZABAPGIT_FULL`.

Called in `fetch_config`:

https://github.com/abaplint/abaplint-abap-backend/blob/661765e887888b4632e82cc2c96448c23fd21bd8/src/zabaplint_ui.fugr.lzabaplint_uif01.abap#L465-L474

**Comment by sbcgua** [comment]
@g-back @larshp
Yeah, seen this one too. Any idea how to fix ? I just had an idea to check program name and if it does not start from `ZABAPGIT` force it to `ZABAPGIT`. Abap backend supposes the full installation of AG so it should work ... but it is a crutch.

**Comment by g-back** [comment]
I have tried this in the debugger, but it does not work either, because the Popup dialog is displayed with dynpro stuff, so it dumps as well.  
I have made a workaround in `zcl_abapgit_password_dialog` by checking if the origin is SCI, and call function `POPUP_GET_USER_PASSWORD` (which is admittedly rather hacky). Not sure how to solve this elegantly

**Comment by larshp** [comment]
need to do a proper decoupling of the UI in abapGit

think there are several open issues for it in abapGit, eg https://github.com/larshp/abapGit/issues/783

**Comment by g-back** [comment]
I'm blind, duplicate of #17 anyway
