### ISSUE TITLE
Issues are not output correctly

### ISSUE THREAD

**Issue by g-back** [abaplint/abaplint-abap-backend#24]
Values are empty in this loop:
https://github.com/abaplint/abaplint-abap-backend/blob/661765e887888b4632e82cc2c96448c23fd21bd8/src/zcl_abaplint_backend.clas.abap#L195-L203

Looks like the prefix is missing `data`-component, see JSON:
![image](https://user-images.githubusercontent.com/27279305/82429054-a0600380-9a8b-11ea-9326-64ca54beac30.png)

Effect:
![image](https://user-images.githubusercontent.com/27279305/82429361-0c426c00-9a8c-11ea-9a2b-723ab3c42986.png)

**Comment by sbcgua** [comment]
yeap, looks like a bug ... will have a look. PRs are also welcome :)

@larshp: did the abaplint issue shape changed recently ? I think it was working before ... or ...?

**Comment by larshp** [comment]
I added some quickfix stuff a while ago, but this is like 3+ weeks ago

**Comment by g-back** [comment]
its a simple fix, will do a PR later
