### ISSUE TITLE
Link in AbapLint error does not work

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-abap-backend#26]
The code-inspector returns this error:
![image](https://user-images.githubusercontent.com/53995991/84649930-a371d680-af07-11ea-9d57-779be3bc89d5.png)

The shortcut is pointing to sapevent:cinav:CLASZCL_ABAPGIT_DEPS|PROGZCL_ABAPGIT_DEPS==============CO|000001

which does not seem to do anything.

**Comment by larshp** [comment]
actually been a very long standing issue for me, also in abapOpenChecks, but fixed in https://github.com/abaplint/abaplint-abap-backend/pull/30

**Comment by ed-holland** [comment]
Was able to test PROG, CLASS, FUGR errors.
PROG and CLASS nicely jumped to the corresponding source code line.
FUGR only shows the main entry point of the function group.
Can this be enhanced? Most of our code is in fubas.

**Comment by larshp** [comment]
some code to be added somewhere around https://github.com/abaplint/abaplint-abap-backend/blob/master/src/zcl_abaplint_check.clas.abap#L161 for handling FUGR
