### ISSUE TITLE
Dependency sources with self signed certificates fail

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-abap-backend#31]
We are using a gitlab server with self-signed certificates.
with git one can define "-c http.sslverify=false" to ignore the error " SSL certificate problem: self signed certificate".

Is it possible to add git options also in the dependencies definition of abaplint.json?

**Comment by larshp** [comment]
the command line `abaplint` uses command line `git` to fetch the dependencies, so try setting the global git configuration before calling abaplint

guess something like https://github.com/larshp/abapGit/blob/master/ci/deploy-merged-build.sh#L14

**Comment by ed-holland** [comment]
Was able to do it in the gitlab runner config
`  pre_clone_script = "git config --global http.sslverify false;git config --global http.proxy $HTTP_PROXY; git config --global https.proxy $HTTPS_PROXY"`
