### ISSUE TITLE
Show the rule that is causing the issue

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-abap-backend#42]
In the message from SCI, the rule is not mentioned that was failing.
`FUGR /JCS/BC > PROG LBTCHDEF [ @518 ] 
Variable "rc_tgt_host_chk_has_failed" not used, #JCS#BC.FUGR.LBTCHDEF.ABAP`

like in the pipeline:
` /tmp/abaplint-aigijg/src/cx_salv_bs_tools_conv_error.clas.abap[1, 1] - Expected CLASSDEFINITION (structure)
`

**Comment by larshp** [comment]
where is the first text from?

also see https://github.com/abaplint/abaplint-cloud-foundry/issues/21

![image](https://user-images.githubusercontent.com/5888506/86009641-be217080-ba1a-11ea-8f04-8bbffb22f520.png)

**Comment by ed-holland** [comment]
We might want to use an other field for the information. We are using the inform method:
![image](https://user-images.githubusercontent.com/53995991/86025501-8f14fa00-ba2e-11ea-9e9f-4bd6a015789b.png)

It contains 4 attribute parameters (only one is used). Or embed it in the message (at the end in round brackets).

[Reference](https://wiki.scn.sap.com/wiki/download/attachments/3669/CI_NEW_CHECK.pdf?api=v2)

**Comment by larshp** [comment]
yea, so embed the abaplint key as last thing in the message text

and then we can hash the message code to SCI_ERRC in order to have the correct grouping

**Comment by larshp** [comment]
try again, latest version of the abap code

**Comment by ed-holland** [comment]
using the latest change (also on docker) shows the rule.
Would propose though to change to `p_text = '&1 (&2)'.` which makes it the same as with abaplint and is also more visible.

When running SCI using ADT the message seems to be messed up
![image](https://user-images.githubusercontent.com/53995991/86147919-432f8700-bafa-11ea-8d10-1f9f3e9ad901.png)

**Comment by ed-holland** [comment]
Had a case where the message is getting to long.
![image](https://user-images.githubusercontent.com/53995991/86152384-60ffea80-bb00-11ea-8aaf-a15ce76d85c8.png)

Would it not be better to remove the file path? or put it at the end or a new line?

**Comment by larshp** [comment]
ATC? please move that to a separate issue

description fixed in https://github.com/abaplint/abaplint-abap-backend/pull/54/commits/765693d99dd6ed7d518802d56be237c9e9be01e9

idea is to only output the filename in some cases, it now handles namespaces, https://github.com/abaplint/abaplint-abap-backend/pull/54/commits/b57c0fb226afa42934baf31a524c0c98b34db94f

**Comment by ed-holland** [comment]
Much better. Thanks
