### ISSUE TITLE
CX_SY_MOVE_CAST_ERROR during dependency serialization

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-abap-backend#62]
Based on Pull Request #61 (for issue 58).

After the dependencies are resolved, the program ZABAPLINT_DEPENDENCIES serializes the code (BUILD_CODE method). It gets the above exception while processing the interface IF_ADT_LIFECYCLE_MANAGER (from SAP).

What is the cause of this exception?
![image](https://user-images.githubusercontent.com/53995991/86485214-740cf780-bd58-11ea-807e-b6252bcbe9c6.png)

**Comment by ed-holland** [comment]
Identified the issue. Translation of senvi needs to take difference between CLAS and INTF.

**Comment by larshp** [comment]
need a PR for it

**Comment by ed-holland** [comment]
It is included in the pull requested mentioned above.
